# Main entrypoint of the workflow.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
include: "./rules/prep_dds.smk"
include: "./rules/DESeq_run.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred :( ---\n")


# target rules
# -----------------------------------------------------
# It is key to understand if updating specific parts of a config can be looked at and cause only certain rules to rerun
# that might be what needs to be executed in this snakefile-
# like if the formula the counts, meta, or formula are changed we rerun from DESeq_run
# but if the color palette for the PCA is changed we only rerun that rule.
rule all:
  input:
    dds=f"{config['projdir']}/{config['resultsdir']}/dds.rds",
    res_workable=f"{config['projdir']}/{config['resultsdir']}/deds.rds"
  default_target: True
