# Main entrypoint of the workflow.


#Learning about filepath references in snakemake I now know that the working directory is
# wherever snakemake cmd is executed, this is the base file path for input: output: log:
# while the input to script: is relative to the rule being executed

# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
include: "rules/prep_dds.smk"
include: "rules/DESeq_run.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred :( ---\n")


# target rules
# -----------------------------------------------------
rule all:
  input:
    dds="results/dds.rds",
    res_workable="results/deds.rds"
  default_target: True
